# Generated by Django 3.2.9 on 2021-12-03 17:26

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Realtor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=70, verbose_name='Имя риэлтора')),
                ('email', models.EmailField(max_length=255, unique=True)),
                ('image', models.ImageField(upload_to='realtors/', verbose_name='Фото риэлтора')),
                ('description', models.TextField(blank=True, max_length=5000, verbose_name='Биография/Описание')),
                ('rating_top', models.BooleanField(default=False, verbose_name='Лучший риэлтор?')),
                ('joined_at', models.DateTimeField(auto_now_add=True, verbose_name='Дата добавления')),
            ],
        ),
    ]
