# Generated by Django 3.2.9 on 2021-12-03 17:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('strainer', '0002_auto_20211203_2033'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='house',
            name='address',
        ),
        migrations.RemoveField(
            model_name='house',
            name='city',
        ),
        migrations.RemoveField(
            model_name='house',
            name='zipcode',
        ),
    ]
