# Generated by Django 3.2.9 on 2021-12-03 17:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('realtor_app', '0001_initial'),
        ('strainer', '0003_auto_20211203_2036'),
    ]

    operations = [
        migrations.AddField(
            model_name='house',
            name='realtors',
            field=models.ManyToManyField(blank=True, related_name='chose_realtor', to='realtor_app.Realtor', verbose_name='Выбрать риэлтора'),
        ),
    ]
